// Generated by `hydrate` from hydrate.features.json. Do not edit: changes are lost on the next
// `hydrate add`, `remove` or `sync`. Listeners live in src/events/listeners/; `hydrate generate listener <event> <name>` adds one.
import type { ListenerDefinition } from "@bun-hydrate/events";
import { welcomeEmailListener } from "./listeners/welcome-email.listener";

/** Every listener, registered on AppEvents by installEvents(). */
export const allListeners: ListenerDefinition[] = [welcomeEmailListener];
