// Generated by `hydrate` from hydrate.features.json. Do not edit: changes are lost on the next
// `hydrate add`, `remove` or `sync`. Jobs live in the *.job.ts files next to it; `hydrate generate job <name>` adds one.
import type { Container } from "@bun-hydrate/di";
import type { JobDefinition } from "@bun-hydrate/queue";
import { AppEvents } from "../events/bus";
import { cleanupExpiredSessionsJob } from "./cleanup-expired-sessions.job";
import { sendWelcomeEmailJob } from "./send-welcome-email.job";

/** Every job defined in this app, e.g. for tests and `hydrate jobs:dispatch`. */
export const allJobs: JobDefinition[] = [cleanupExpiredSessionsJob, sendWelcomeEmailJob];

/** What the worker runs: the jobs above, plus the jobs behind durable event listeners. */
export function workerHandlers(container: Container): JobDefinition[] {
  return [...allJobs, ...container.get(AppEvents).jobs()];
}
