// Generated by `hydrate` from hydrate.features.json. Do not edit: changes are lost on the next
// `hydrate add`, `remove` or `sync`. Pages live in src/web/pages/auth/.
import { Login } from "./pages/auth/Login";

/** Spread into definePages(): `definePages({ ...yourPages, ...authPages })`. */
export const authPages = { Login };

/** Serve them: `for (const page of authPageRoutes) router.get(page.path, (ctx) => react.render(page.name, {}, { title: page.title, ctx }))`. */
export const authPageRoutes = [
  { path: "/login", name: "Login", title: "Sign in" },
] as const;
