// Generated by `hydrate` from hydrate.features.json. Do not edit: changes are lost on the next
// `hydrate add`, `remove` or `sync`. Pass clientPlugins to hydrate.config.ts and createAssets() in src/main.ts.
import type { ClientPlugin } from "@bun-hydrate/react";
import { sassPlugin } from "@bun-hydrate/react/sass";

/** The client bundle's Bun plugins, the same in `hydrate dev` and `hydrate build`. */
export const clientPlugins: ClientPlugin[] = [sassPlugin()];
