// Generated by `hydrate` from hydrate.features.json. Do not edit: changes are lost on the next
// `hydrate add`, `remove` or `sync`. Each capability lives in its own file next to it.
import type { App } from "@bun-hydrate/core";
import type { Container } from "@bun-hydrate/di";
import { installMetrics } from "./metrics";
import { installCors } from "./cors";
import { installRateLimit } from "./rate-limit";

/** Call once in src/app.ts, before installAuth() and your routes: installPlatform(app, container). */
export function installPlatform(app: App, container: Container): void {
  installMetrics(app);
  installCors(app);
  installRateLimit(app);
}
