/** Helpers for rendering orchestrator-owned files. */

export interface NamedImport {
  from: string;
  name: string;
}

/** The first lines of every wholly generated file. */
export function generatedHeader(instead: string): string {
  return [
    "// Generated by `hydrate` from hydrate.features.json. Do not edit: changes are lost on the next",
    `// \`hydrate add\`, \`remove\` or \`sync\`. ${instead}`,
  ].join("\n");
}

/** One import line per module, packages before relative paths, names sorted within a line. */
export function renderImports(imports: readonly NamedImport[]): string[] {
  const byModule = new Map<string, Set<string>>();
  for (const { from, name } of imports) byModule.set(from, (byModule.get(from) ?? new Set()).add(name));
  const modules = [...byModule.keys()];
  const ordered = [...modules.filter((from) => !from.startsWith(".")), ...modules.filter((from) => from.startsWith("."))];
  return ordered.map((from) => `import { ${[...byModule.get(from)!].sort().join(", ")} } from "${from}";`);
}
