// Generated by `hydrate` from hydrate.features.json. Do not edit: changes are lost on the next
// `hydrate add`, `remove` or `sync`. Commands live in the *.commands.ts files next to it.
import type { CommandHandler } from "@bun-hydrate/cli/commands";
import { permissionsCommand, setRoleCommand } from "./core.commands";
import { createUserCommand } from "./passwords.commands";
import { revokeSessionsCommand } from "./sessions.commands";

/** Run with `bun hydrate <name>`; the CLI opens the database from DATABASE_URL. */
export const commands: Record<string, CommandHandler> = {
  "auth:set-role": setRoleCommand,
  "auth:permissions": permissionsCommand,
  "auth:create-user": createUserCommand,
  "auth:revoke-sessions": revokeSessionsCommand,
};
