// Generated by `hydrate` from hydrate.features.json. Do not edit: changes are lost on the next
// `hydrate add`, `remove` or `sync`. Customize src/auth/config.ts instead.
import type { Context } from "@bun-hydrate/core";
import { createAuth } from "@bun-hydrate/auth";
import { sessionsFeature } from "@bun-hydrate/auth/features";
import { authConfig } from "./config";
import { coreFeature } from "./core";
import { passwordsFeature } from "./passwords";
import { loginFeature } from "./login/feature";

export const auth = createAuth({
  config: authConfig,
  features: [
    coreFeature,
    passwordsFeature,
    sessionsFeature(authConfig.features?.sessions),
    loginFeature,
  ],
});

/** Call once in src/app.ts: `installAuth(app, container)`. The container needs Database. */
export const installAuth = auth.install;

/** For createReactRenderer({ shared: authShared }): pages render signed in from the first paint. */
export const authShared = (ctx: Context<any>) => ({ auth: auth.snapshot(ctx) });
